{ pkgs, lib, config, ... }:

{
  home.packages = with pkgs; [
    ghostty
  ];

  # Ghostty configuration
  home.file.".config/ghostty/config".text = ''
    # Ghostty Configuration
    # Generated by NixOS/Home Manager with Stylix integration

    # Font configuration
    font-family = ${config.stylix.fonts.monospace.name}
    font-size = ${builtins.toString config.stylix.fonts.sizes.terminal}

    # Color scheme (using Stylix colors)
    background = #${config.lib.stylix.colors.base00}
    foreground = #${config.lib.stylix.colors.base07}
    
    # Normal colors
    color-0 = #${config.lib.stylix.colors.base00}
    color-1 = #${config.lib.stylix.colors.base08}
    color-2 = #${config.lib.stylix.colors.base0B}
    color-3 = #${config.lib.stylix.colors.base0A}
    color-4 = #${config.lib.stylix.colors.base0D}
    color-5 = #${config.lib.stylix.colors.base0E}
    color-6 = #${config.lib.stylix.colors.base0C}
    color-7 = #${config.lib.stylix.colors.base05}
    
    # Bright colors
    color-8 = #${config.lib.stylix.colors.base03}
    color-9 = #${config.lib.stylix.colors.base09}
    color-10 = #${config.lib.stylix.colors.base01}
    color-11 = #${config.lib.stylix.colors.base02}
    color-12 = #${config.lib.stylix.colors.base04}
    color-13 = #${config.lib.stylix.colors.base06}
    color-14 = #${config.lib.stylix.colors.base0F}
    color-15 = #${config.lib.stylix.colors.base07}

    # Cursor
    cursor = #${config.lib.stylix.colors.base07}
    cursor-style = beam
    cursor-blink = true

    # Window settings
    window-padding-x = 10
    window-padding-y = 10
    window-decoration = false
    background-opacity = 0.9
    background-blur = 10

    # Performance
    gpu-acceleration = true
    vsync = true
    max-fps = 144

    # Input
    keybind = ctrl+shift+c=copy
    keybind = ctrl+shift+v=paste
    keybind = ctrl+shift+t=new-tab
    keybind = ctrl+shift+w=close-tab
    keybind = ctrl+shift+left=previous-tab
    keybind = ctrl+shift+right=next-tab
    keybind = ctrl+shift+enter=new-window
    keybind = ctrl+shift+q=quit

    # Tab bar
    tab-bar = true
    tab-bar-style = powerline
    tab-bar-padding = 5

    # Shell integration
    shell-integration = true
    shell-integration-features = no-cursor,no-title

    # Bell
    bell = none

    # Selection
    selection-include-trailing-spaces = false
    selection-foreground = #${config.lib.stylix.colors.base00}
    selection-background = #${config.lib.stylix.colors.base0D}

    # URL detection
    url-style = single
    url-color = #${config.lib.stylix.colors.base0D}
    url-prefix = https://,http://,ftp://,file://

    # Mouse
    mouse-hide-while-typing = true
    pointer-style = default

    # Performance tuning
    repaint-delay = 10
    input-delay = 0
    sync-to-monitor = false

    # Wayland specific
    wayland-titlebar-color = #${config.lib.stylix.colors.base00}
    wayland-app-id = ghostty
    wayland-enable-vsync = true

    # X11 specific
    x11-titlebar-color = #${config.lib.stylix.colors.base00}
    x11-enable-vsync = true

    # Logging
    log-level = warning
    log-file = ~/.local/share/ghostty/ghostty.log

    # Theme-specific adjustments
    ${lib.optionalString (config.stylix.polarity == "dark") ''
    # Dark theme specific settings
    background-blur = 15
    background-opacity = 0.85
    ''}
    ${lib.optionalString (config.stylix.polarity == "light") ''
    # Light theme specific settings
    background-blur = 5
    background-opacity = 0.95
    ''}
  '';

  # Enable stylix integration for Ghostty
  stylix.targets.ghostty.enable = true;
} 